import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

export default function Home() {
  return (
      <>
        <Head>
          <title>BLog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Wrapper>


          <Logo>

            <Image
            src="/logo.svg"
            alt="logo"
            layout="fill"
            objectFit='contain'
            />

          </Logo>


        </Wrapper>

      </>
  )
}

const Wrapper = styled.section`
  width: 100vw;
  height: 100vh;
  background: radial-gradient(59.95% 59.95% at 50% 100%, #C40052 0%, #1D0F14 100%);
  display: flex;
  flex-direction: column;
  gap: 15px;
  align-items: center;
  justify-content: center;
`

const Logo = styled.div`
  width: 300px;
  height:150px;
  position: relative;
`